azure:
  activedirectory:
    client-id: 84fabf81-c786-4a4d-ba9c-40df2637dfb0
    client-secret: 7E5xZ34.ld__cuVnW9oagOmc-nTxS53N.y
    tenant-id: 1dc8ab2b-9e72-43d0-b912-21b8fb4a9bd2
    app-id-uri: http://localhost:8080
    authorization-clients:
      myregistrationid:
        scopes:
          - api://3ba786ec-e334-4681-89f0-8e4ba399194a/user_impersonation

webapp:
  registered-endpoints:
    webapi: http://localhost:8081/user